# Predicting House Prices (One feature)

 In this notebook we will use data on house sales in King County, where Seattle is located, to predict house prices using simple (one feature) linear regression. You will:

 Use SArray and SFrame functions to compute important summary statistics
 Write a function to compute the Simple Linear Regression weights using the closed form solution
 Write a function to make predictions of the output given the input feature
 Turn the regression around to predict the input/feature given the output
 Compare two different models for predicting house prices

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [28]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float,
              'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str,
              'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int,
              'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

In [29]:
url1='C:\Users\emman\Machine Learning\Course 2\kc_house_train_data.csv'
url2='C:\Users\emman\Machine Learning\Course 2\kc_house_test_data.csv'

SyntaxError: invalid syntax (<ipython-input-29-b271b72df53a>, line 1)

In [32]:
sales_train=pd.read_csv(url1, dtype=dtype_dict)
sales_test=pd.read_csv(url2, dtype=dtype_dict)

In [33]:
sales_train.head()
sales_test.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  0114101516  20140528T000000  310000.0       3.0        1.0       1430.0   
1  9297300055  20150124T000000  650000.0       4.0        3.0       2950.0   
2  1202000200  20141103T000000  233000.0       3.0        2.0       1710.0   
3  8562750320  20141110T000000  580500.0       3.0        2.5       2320.0   
4  7589200193  20141110T000000  535000.0       3.0        1.0       1090.0   

   sqft_lot floors  waterfront  view     ...      grade  sqft_above  \
0     19901    1.5           0     0     ...          7        1430   
1      5000      2           0     3     ...          9        1980   
2      4697    1.5           0     0     ...          6        1710   
3      3980      2           0     0     ...          8        2320   
4      3000    1.5           0     0     ...          8        1090   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1927             0    98028  47.7558 -122.229   
1            970      1979             0    98126  47.5714 -122.375   
2              0      1941             0    98002  47.3048 -122.218   
3              0      2003             0    98027  47.5391 -122.070   
4              0      1929             0    98117  47.6889 -122.375   

   sqft_living15  sqft_lot15  
0         1780.0     12697.0  
1         2140.0      4000.0  
2         1030.0      4705.0  
3         2580.0      3980.0  
4         1570.0      5080.0  

[5 rows x 21 columns]

# Write a generic function that accepts a column of data (e.g, an SArray) ‘input_feature’ and another column ‘output’ and returns the Simple Linear Regression parameters ‘intercept’ and ‘slope’. Use the closed form solution from lecture to calculate the slope and intercept. e.g. in python:

In [38]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
def simple_linear_regression( inputfeature, output):
    x = np.asanyarray(inputfeature)
    y = np.asanyarray(output)
    regr.fit (x, y)
    slope=regr.coef_
    intercept=regr.intercept_
    return(slope, intercept)

In [39]:
inputfeature=sales_train[['sqft_living']]
output=sales_train[['price']]
simple_linear_regression(inputfeature, output)

(array([[ 281.95883963]]), array([-47116.07907289]))

In [41]:
squarefeet_slope,squarefeet_intercept=(simple_linear_regression(inputfeature,output))

# Write a function that accepts a column of data ‘input_feature’, the ‘slope’, and the ‘intercept’ you learned, and returns an a column of predictions ‘predicted_output’ for each entry in the input column. e.g. in python:

In [40]:
def get_regression_predictions(input_feature, intercept, slope):
    prediction=input_feature*slope+intercept
    return(prediction)

# Using your Slope and Intercept from (4), What is the predicted price for a house with 2650 sqft?

In [44]:
input_feature=2650
intercept=squarefeet_intercept
slope=squarefeet_slope
get_regression_predictions(input_feature, intercept, slope)

array([[ 700074.84594751]])

# Write a function that accepts column of data: ‘input_feature’, and ‘output’ and the regression parameters ‘slope’ and ‘intercept’ and outputs the Residual Sum of Squares (RSS). e.g. in python:

In [51]:
def get_residual_sum_of_square(input_feature, output, intercept, slope):
    x = np.asanyarray(input_feature)
    y = np.asanyarray(output)
    y_hat=regr.predict (x)
    RSS=np.sum((y-y_hat)**2)
    return(RSS)

# According to this function and the slope and intercept from (4) What is the RSS for the simple linear regression using squarefeet to predict prices on TRAINING data?

In [52]:
get_residual_sum_of_square(sales_train[['sqft_living']], sales_train[['price']],intercept=squarefeet_intercept,
slope=squarefeet_slope )


1201918354177283.0

# Write a function that accept a column of data:‘output’ and the regression parameters ‘slope’ and ‘intercept’ and outputs the column of data: ‘estimated_input’. Do this by solving the linear function output = intercept + slope*input for the ‘input’ variable (i.e. ‘input’ should be on one side of the equals sign by itself). e.g. in python:



In [54]:
def inverse_regression_predictions(output, intercept, slope):
    estimated_input=(output-intercept)/slope
    return(estimated_input)

# Quiz Question: According to this function and the regression slope and intercept from (3) what is the estimated square-feet for a house costing $800,000?

In [55]:
output=800000
inverse_regression_predictions(output, intercept, slope)

array([[ 3004.39624515]])

# Instead of using ‘sqft_living’ to estimate prices we could use ‘bedrooms’ (a count of the number of bedrooms in the house) to estimate prices. Using your function from (3) calculate the Simple Linear Regression slope and intercept for estimating price based on bedrooms. Save this slope and intercept for later (you might want to call them e.g. bedroom_slope, bedroom_intercept).

In [56]:
inputfeature=sales_train[['bedrooms']]
output=sales_train[['price']]
simple_linear_regression(inputfeature, output)

(array([[ 127588.95293399]]), array([ 109473.17762296]))

In [57]:
bedroom_slope,bedroom_intercept=(simple_linear_regression(inputfeature,output))

# Now that we have 2 different models compute the RSS from BOTH models on TEST data.

In [61]:
get_residual_sum_of_square(sales_test[['sqft_living']], sales_test[['price']],intercept=squarefeet_intercept,
slope=squarefeet_slope )


3.5285983689210017e+20

In [60]:
get_residual_sum_of_square(sales_test[['bedrooms']], sales_test[['price']],intercept=bedroom_intercept,
slope=bedroom_slope )


493364585960300.62